### ISSUE TITLE
[Docs] magic search returning outdated package metadata for pytorch (M2 Macbook Air)

### ISSUE THREAD

**Issue by friediisch** [modularml/max#245]
### Where is the problem?

https://docs.modular.com/max/tutorials/magic

### What can we do better?

When overwriting the `pytorch` installation from `conda-forge` installation with the one from the `pytorch` channel, the `magic.lock` file shows the correct package metadata:

```
  kind: conda
  name: pytorch
  version: 2.5.0
  build: py3.12_0
  subdir: osx-arm64
  url: https://conda.anaconda.org/pytorch/osx-arm64/pytorch-2.5.0-py3.12_0.tar.bz2
  sha256: 3787d3a51ef1d614a2e6efa5878f53d9749c753f04a46bda768fac655585018f
  md5: dcac54f8936135aad561ebb635dba1f7
  depends:
  - filelock
  - jinja2
  - llvm-openmp <16
  - networkx
  - python >=3.12,<3.13.0a0
  - pyyaml
  - sympy
  - typing_extensions
  constrains:
  - cpuonly
  license: BSD 3-Clause
  license_family: BSD
  size: 62105250
  timestamp: 1728933144481
```
  
  However when running the `magic search pytorch` command, the old metadata from the `conda-forge` channel is displayed:

```  
Using channels: pytorch, conda-forge, https://conda.modular.com/max/

pytorch cpu_generic_py39hd3c670c_2
----------------------------------

Name                pytorch            
Version             2.4.1
Build               cpu_generic_py39hd3c670c_2
Size                21600712           
License             BSD-3-Clause       
Subdir              osx-arm64          
File Name           pytorch-2.4.1-cpu_generic_py39hd3c670c_2.conda
URL                 https://conda.anaconda.org/conda-forge/osx-arm64/pytorch-2.4.1-cpu_generic_py39hd3c670c_2.conda
MD5                 ca92192bc91b324aaab5f3c73de64884
SHA256              4b41b41d5247e4b58dca29c1160d25783c747495bdcc92a314fc5958e988b9e9

Dependencies:
 - __osx >=11.0
 - filelock
 - fsspec
 - jinja2
 - libabseil * cxx17*
 - libabseil >=20240722.0,<20240723.0a0
 - libcblas >=3.9.0,<4.0a0
 - libcxx >=17
 - liblapack >=3.9.0,<4.0a0
 - libprotobuf >=5.27.5,<5.27.6.0a0
 - libtorch 2.4.1.*
 - libuv >=1.49.1,<2.0a0
 - llvm-openmp >=17.0.6
 - networkx
 - nomkl
 - numpy >=1.19,<3
 - python >=3.9,<3.10.0a0
 - python >=3.9,<3.10.0a0 *_cpython
 - python_abi 3.9.* *_cp39
 - sleef >=3.7,<4.0a0
 - sympy >=1.13.1
 - typing_extensions >=4.8.0
```

Steps to reproduce (on M2 Macbook Air):
- `magic init hello-magic --format mojoproject`
- `cd hello-magic`
- `magic add pytorch`
- Edit channels in `mojoproject.toml` to `channels = ["pytorch", "conda-forge", "https://conda.modular.com/max"]`
- `magic remove pytorch`
- `magic add pytorch`
- `magic search pytorch`

### Anything else?

Huge fan of the project 🔥
